### ISSUE TITLE
Cascades not currently built into DB

### ISSUE THREAD

**Issue by alclary** [CS467-S24-TravelPlanner/travelplanner#31]
I don't believe we currently have cascades built in to the DB. For example, if a User is deleted, all their trips, all *their* experiences, and all the tripExperience rows associated with them should also be removed.

I believe this would be some sort of sequelize model definition, but am not immediately sure.

**Comment by ChaseSmith67** [comment]
I dug into the Sequelize documentation a bit. It seems that many-to-many relationships default to Cascade for both On Delete and On Update. It seems fairly trivial to change either or both of these settings for any of the models.

One thought: for Users in particular, we could just not allow an actual User deletion to be completed. Rather, the username/email is updated to "Deleted User" or something similar and they will no longer be able to access that account. This is more or less how Discord or Reddit and similar services handle it, at least partially to account for the example you described, so Experiences and even Trips won't be removed.

**Comment by alclary** [comment]
^ Functional with Sequelize at the moment.
