### ISSUE TITLE
Authorization and Authentication Decision

### ISSUE THREAD

**Issue by alclary** [CS467-S24-TravelPlanner/travelplanner#9]
Need team input please. If we want to utilize OAuth 2.0 we could either utilize a service like Auth0 or use Google credential management----although I believe Google's system constrains users to using/creating a Google account. However, if you think otherwise, please let me know. 

Please provide your thoughts as comments, as this decision will influence the schema for the Users table in the DB.

**Comment by alclary** [comment]
In favor of moving this item forward. I vote that we utilize Auth0. Any of us who took 493 should be somewhat familiar with it. 

Regardless of which authorization/authentication platform we use, some additions to the API and API caller functions will need to be made to facilitate checking of JWTs. While it will take some refactoring, we can wait on that until a few frontend pages are built.

**Comment by ChaseSmith67** [comment]
Authorization solutions aren't really my area of expertise, so whatever the group thinks is best works for me. Looking over Auth0, it seems like it will be fine for our purposes.

I think refactoring the existing API and associated functions should be easy enough. We might be able to write a authorization check function and just call it for validation when needed prior to making any API calls from the frontend.

**Comment by alclary** [comment]
Seems to be consensus that Auth0 is the way to go. It appears that Akash has been working on login separately, will need to first review what work has been done on Akash's branch before moving forward.

**Comment by alclary** [comment]
At this point in time, we have pivoted to utilize Google Identity Services as the primary ease-of-use authentication service. We have a Login page constructed and could feasibly integrate local registration and authentication also with a token based approach. However, that integration will depend on time considerations.
